### ISSUE TITLE
Create static HTML prototype for demonstration.

### ISSUE THREAD

**Issue by l-gothberg** [osu-cascades/coic-housing-survey#3]

**Comment by l-gothberg** [comment]
Currently working on low-resolution prototype using proto.io.  Current progress can be found here: https://pr.to/216LDE/

**Comment by ybakos** [comment]
NO. You should be creating a prototype with static html right here in GH.

**Comment by l-gothberg** [comment]
Complete.  Forgot to include closeout on commit comment.
